---
- hosts: all
  connection: ansible.netcommon.netconf
  tasks:
    - name: Set Media Channels Config
      ansible.netcommon.netconf_config:
        target: candidate
        backup: yes
        backup_options:
          dir_path: "{{ backup_dir }}"
          filename: "{{ backup_file }}"

        content: "{{ lookup('file', '{{ configuration_file }}') }}"